# Generated by Django 5.0.2 on 2024-02-16 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='background_color',
            field=models.TextField(blank=True, default='#ffffff', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='text_color',
            field=models.TextField(blank=True, default='#000000', max_length=10, null=True),
        ),
    ]
